### PR TITLE
Fixed dark and light css typos

### PR DESCRIPTION
**Pull request by lightmaster**
Whatever program you're using tends to make very very long lines in CSS files, so I used [codeanywhere's](http://codeanywhere.com) "Beautify" option to make it easier to read, and then edited the original files so the formatting wasn't messed up from how you had it. It's difficult to show exactly what typos I found since there are no useful line numbers in the original files, and github does a bad job of showing the exact changes on long lines, but here's a list of the typos I found:

1. `postion` is misspelled, but there's another `position` tag directly after it so that first `postion` is removed.
2. several color values of `2d3a4b);`
3. a tag missing the `;` between `antialiasedleft`
4. `bototm` being misspelled
5. the opening bracket in `[exact]` was missing in one of the occurances.
6. several leading `,`'s that were unnecessary
7. a color value having an extra `#` in it.

### CODE REVIEW

**Comment by weather34** [comment]
good morning , interesting I just switched to a new online minifier http://cnvyr.io/online last week  I used to use the extension option in Coda2 . however both files need a good clean out , ive tried in recent months to strip out all unnecessary code but its time consuming and tedious , every new option added over the years requires additional css but some of those options are no longer used so needs a good clean ideally it should be sub 100kb when compressed thinks its around 110kb at present so its not far off.. on my own site they are sub 90kb as I dont use all the options or have any need as to what is in the download version..many thanks again for taking the time to resolve some issues..brian

**Comment by lightmaster** [comment]
Closing this PR since you've made the changes.

**Comment by weather34** [comment]
ok there is a brand new option an idea by derek so look out for that one tomorrow doesnt effect settings1.php,but does have new option in setup screen and index.php will let it run for a day see if i can spot any anomalies.. in use at https//:weather34.com at the moment 
F6264BCA-0B8C-4396-B8AA-5B0FFA080FB0

**Comment by weather34** [comment]
can you drop me an email ? i have an idea

**Comment by lightmaster** [comment]
What is your email?

**Pull request closed without merging**
